[theme]

primaryColor = "#45A29E" 
backgroundColor = "#0B0C10"
secondaryBackgroundColor = "#1F2833"
textColor = "#C5C6C7"
font = "sans serif"

[server]

headless = true
enableCORS = false
enableXsrfProtection = false